### PR TITLE
Added jQuery lightbox support to view embeddings(screenshots)

### PR DESCRIPTION
**Pull request by BogdanLivadariu**
This is how a screenshot is displayed now:
reportoverview
reportoverview2

after you click on the image:
reportoverviewwithlightbox

### CODE REVIEW

**Comment by bogdanmolocea** [comment]
Looks nice

**Comment by ascripcaru** [comment]
It looks very useful :+1:

**Comment by BogdanLivadariu** [comment]
@kingsleyh when would this enhancement end up in a new release ?

**Comment by kingsleyh** [comment]
it will go in the next release - which will be probably next week sometime.

—K

**Comment by BogdanLivadariu** [comment]
Thanks, looking fw seeing this in :)

**Pull request merged**
