### PR TITLE
Gherkin syntax is not properly HTML escaped

### PR DESCRIPTION
**Pull request by damianszczepanik**
Issue #49

### CODE REVIEW

**Comment by kingsleyh** [comment]
thanks for your contributions and help damian - you are AWESOME! As you can see I have had zero time to work on this project since having my baby daughter 2 years ago!

**Comment by damianszczepanik** [comment]
Hope you have some time soon to make new release since this is why I'm preparing PRs for this and that's what other users expect (#84).

We are using cucumber reports everyday so I have some idea how to improve it and make more and more friendly!

**Comment by kingsleyh** [comment]
good job :)

I can make a new release on the following condition:

 -- The master branch of cucumber reports works with the jenkins cucumber plugin, the maven mojo and cucumber-sandwich on master and slave without any new issues or major problems.

This is because I have no time to regression test this which is one of the major reasons I don't manage to release often.

Let me know approx when you want a new release and I will try to be prepared for it. 

Thanks

--K

**Comment by damianszczepanik** [comment]
Sounds good. I should be ready within 3-4 weeks.

If you advice me how to build binary which I can test locally on Jenkins that would be great.

**Comment by kingsleyh** [comment]
build cucumber reports locally - and then in the jenkins project pom change the version of cucumber reports to the one you built locally and then run mvn clean install and it should produce an hpi in the target directory - use that hpi in a locally running jenkins

**Comment by damianszczepanik** [comment]
mvn install produced jar file not hpi - are you sure about the command?

I can't figure out what is the goal based on information from pom.xml file so your help is welcome :-)

**Pull request merged**
